linters-settings:
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 120
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - exitAfterDefer
      - whyNoLint
      - appendAssign
      - octalLiteral
      - httpNoBody
      - unnecessaryBlock # for UUID encoder
      - paramTypeCombine # https://github.com/go-critic/go-critic/issues/1248, waiting for 0.6.5 bundled with golangci-lint

linters:
  enable:
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - revive
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - unused
    # Do not enable:
    # - wsl       (too opinionated about newlines)
    # - godox     (todos are OK)
    # - bodyclose (false positives on helper functions)
    # - prealloc  (not worth it in scope of this project)
    # - maligned  (same as prealloc)
    # - funlen    (gocyclo is enough)
    # - gochecknoglobals (we know when it is ok to use globals)
    # - gochecknoinits (we know when it is ok to use inits)
    # - dupl (validator/parser package are false positive)


issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude go:generate from lll
    - source: "//go:generate"
      linters: [ lll ]

    # Exclude links from lll
    - source: "// See https://"
      linters: [ lll ]

    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - lll
    - path: _test\.go
      linters: [ unparam ]
      text: .*\$\d? # Do not warn about unused closure parameters in test files.

    # Ignore shadowing of err.
    - linters: [ govet ]
      text: 'declaration of "(err|ctx|log)"'

    # Ignore linters in main packages.
    - path: cmd\/.+\/main\.go
      linters: [ goconst, funlen, gocognit, gocyclo ]

    # TODO(tdakkota): add comments?
    - path: (conv|uri|gen|otelogen)
      linters: [ revive, golint ]
      text: "(should have comment.+or be unexported|comment on exported)"

    # We don't need package comments for internal packages.
    # We don't need comments for command packages.
    - path: .*(cmd|tools|internal)(\/|\\).*
      linters: [ revive, golint ]
      text: "should have (comment.+or be unexported|a package comment)"

    # Intended in commands:
    # G307: Deferring unsafe method "Close" on type "*os.File"
    # G304: Potential file inclusion via variable
    - path: .*(cmd|tools)(\/|\\).+(\/|\\).+\.go
      text: G(304|306|307)

    # Nobody cares.
    # G114: Use of net/http serve function that has no support for setting timeouts
    - path: techempower(\/|\\)main.go
      text: G114

    # We are using quoting algorithm from mime/multipart package. False-positive.
    - path: http(\/|\\)file\.go
      linters: [ gocritic ]
      text: sprintfQuotedString

    # Not supposed to be constant.
    - linters: [ goconst ]
      text: 'string `(string|number|u?int\d{0,2})`'
    - linters: [ goconst ]
      text: 'string `(Unix|unix|date|time)'

    - linters: [ revive ]
      text: "if-return: redundant if ...; err != nil check, just return error instead."

