openapi: 3.0.0
info:
  title: Test schema
  version: 0.1.0
paths:
  /{shortURL}:
    get:
      parameters:
        - name: shortURL
          in: path
          required: true
          content:
            '*/*':
              schema:
                type: string
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: string
