name: Coverage
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          cache: true

      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Run tests with coverage
        run: make coverage

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: profile.out
          if-no-files-found: error
          retention-days: 1

      - name: Send coverage
        uses: codecov/codecov-action@v3
        with:
          file: profile.out

  upload:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Send coverage
        uses: codecov/codecov-action@v3
        with:
          file: profile.out
